export const MOCK_USER_ID = '550e8400-e29b-41d4-a716-446655440000';

export const MOCK_PROFILE = {
  id: MOCK_USER_ID, did: 'did:continu:a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
  displayName: 'Arjun Sharma', email: 'arjun.sharma@example.com',
  walletAddress: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e',
  avatarUrl: null, isActive: true, createdAt: new Date('2022-06-15'),
};

export const MOCK_CREDENTIALS = [
  { id:'vc-001', userId:MOCK_USER_ID, domain:'education', issuer:'MIT Digital Credentials', issuerDid:'did:continu:mit0edu000000001', credentialType:'BachelorsDegree', credentialSubject:{ degree:'B.Tech Computer Science', institution:'MIT', graduationYear:2022, gpa:3.8, honors:'Magna Cum Laude' }, proof:{ type:'Ed25519Signature2020', verificationMethod:'did:continu:mit#key-1' }, zkpProof:'zkp_ed25519_abc123def456ghi789', status:'active', isShared:false, expiresAt:null, issuedAt:new Date('2022-06-15'), createdAt:new Date('2022-06-15') },
  { id:'vc-002', userId:MOCK_USER_ID, domain:'employment', issuer:'Google LLC HR', issuerDid:'did:continu:google000000001', credentialType:'EmploymentRecord', credentialSubject:{ role:'Senior Software Engineer', company:'Google LLC', startDate:'2022-08-01', department:'Cloud Infrastructure', clearanceLevel:'L5' }, proof:{ type:'Ed25519Signature2020', verificationMethod:'did:continu:google#key-1' }, zkpProof:'zkp_ed25519_def456ghi789jkl012', status:'active', isShared:true, expiresAt:null, issuedAt:new Date('2022-08-01'), createdAt:new Date('2022-08-01') },
  { id:'vc-003', userId:MOCK_USER_ID, domain:'healthcare', issuer:'Apollo Hospitals', issuerDid:'did:continu:apollo00000001', credentialType:'HealthRecord', credentialSubject:{ bloodType:'O+', allergies:['Penicillin'], vaccinations:['COVID-19 (2x)','Influenza 2024'], primaryPhysician:'Dr. Sharma', fhirRecordId:'FHIR-2024-ABC' }, proof:{ type:'Ed25519Signature2020', verificationMethod:'did:continu:apollo#key-1' }, zkpProof:'zkp_ed25519_ghi789jkl012mno345', status:'active', isShared:false, expiresAt:new Date('2025-12-31'), issuedAt:new Date('2024-01-10'), createdAt:new Date('2024-01-10') },
  { id:'vc-004', userId:MOCK_USER_ID, domain:'finance', issuer:'HDFC Bank', issuerDid:'did:continu:hdfc000000001', credentialType:'CreditScoreAttestation', credentialSubject:{ creditScore:780, bureau:'CIBIL', scoreRange:'300-900', assessmentDate:'2024-11-01', category:'Excellent' }, proof:{ type:'Ed25519Signature2020', verificationMethod:'did:continu:hdfc#key-1' }, zkpProof:'zkp_ed25519_jkl012mno345pqr678', status:'active', isShared:false, expiresAt:new Date('2025-11-01'), issuedAt:new Date('2024-11-01'), createdAt:new Date('2024-11-01') },
  { id:'vc-005', userId:MOCK_USER_ID, domain:'identity', issuer:'Govt. of India – UIDAI', issuerDid:'did:continu:uidai00000001', credentialType:'NationalIdentity', credentialSubject:{ aadhaarLinked:true, kycStatus:'Verified', panLinked:true, digilockerVerified:true, residenceProof:'Maharashtra, India' }, proof:{ type:'Ed25519Signature2020', verificationMethod:'did:continu:uidai#key-1' }, zkpProof:'zkp_ed25519_mno345pqr678stu901', status:'active', isShared:false, expiresAt:null, issuedAt:new Date('2023-03-15'), createdAt:new Date('2023-03-15') },
];

export const MOCK_PREDICTIONS = [
  { id:'pred-001', userId:MOCK_USER_ID, transitionType:'education_to_employment', title:'Career Acceleration Window', description:'Your credential profile suggests high readiness for a senior engineering role transition.', insight:{ summary:'Based on your L5 tenure at Google (2+ years) and MIT credentials, you are in the top 12% salary negotiation position for principal engineer roles.', dataPoints:['2.3 years avg tenure at current role','Top 8% skill match for Staff Eng roles','ML/AI skills gap detected'], recommendation:'Upskill in LLM fine-tuning to maximize leverage.' }, confidence:'0.87', timeframe:'6-12 months', actionItems:['Complete Google ML cert','Update LinkedIn with FHIR project','Connect with 3 target companies'], isActioned:'pending', createdAt:new Date('2024-12-01') },
  { id:'pred-002', userId:MOCK_USER_ID, transitionType:'financial_milestone', title:'Home Loan Pre-Approval Readiness', description:'Your financial credentials show strong eligibility for a ₹1.2–1.8 Cr home loan.', insight:{ summary:'CIBIL 780, stable employment, and FOIR under 35% places you in the best rate bracket with 6 major lenders.', dataPoints:['Credit score: 780 (Excellent)','Employment: 2.5 years stable','FOIR: 28% (healthy)'], recommendation:'Apply within 90 days to lock current rates before Q1 2025 RBI review.' }, confidence:'0.92', timeframe:'1-3 months', actionItems:['Get income verification VC from employer','Compare rates across 6 lenders','Prepare property documents'], isActioned:'actioned', createdAt:new Date('2024-11-15') },
  { id:'pred-003', userId:MOCK_USER_ID, transitionType:'employment_to_healthcare', title:'Preventive Health Screening Alert', description:'Cross-domain analysis indicates elevated stress indicators from employment pattern.', insight:{ summary:'Extended high-work-intensity periods correlate with 2.1x cardiovascular risk increase in your demographic profile.', dataPoints:['Work hours: 58/week avg','Last health checkup: 14 months ago','Age bracket: preventive screening recommended'], recommendation:'Schedule comprehensive health panel within 30 days.' }, confidence:'0.74', timeframe:'Immediate', actionItems:['Book Apollo Health Checkup','Share health VC with primary physician','Enable wearable data sync'], isActioned:'pending', createdAt:new Date('2024-12-10') },
];